(() => {
  const $ = (selector, root = document) => root.querySelector(selector);
  const $$ = (selector, root = document) => [...root.querySelectorAll(selector)];
  const state = { view: location.hash.slice(1) || 'today', courses: [], courseId: '', due: [], selectedIntake: null, pendingFiles: [], bankPreview: null, politicsItems: [], politicsIndex: 0 };
  const views = ['today', 'review', 'capture', 'knowledge', 'settings'];
  const labels = { today: ['学习台 · 今日', '今天，先还一笔知识债'], review: ['错题回测', '复习不是浏览，是再次作答'], capture: ['图片优先收录', '一题多图，先把原始证据留下'], knowledge: ['知识与题库', '按课程工作，不把四门课混成一棵树'], settings: ['独立设置', '模型只负责提出草稿'] };
  const errorLabels = { knowledge_gap: '知识点不会', method_selection: '方法选择错误', derivation_calculation: '推导或计算出错' };
  const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
  const text = value => String(value ?? '').trim();
  const data = async (url, options) => { const response = await fetch(url, options); const body = await response.json().catch(() => ({})); if (!response.ok || body.error) throw new Error(body.error?.message || `请求失败（${response.status}）`); return body.data; };
  const toast = message => { const node = $('#toast'); node.textContent = message; node.classList.add('is-visible'); clearTimeout(toast.timer); toast.timer = setTimeout(() => node.classList.remove('is-visible'), 2600); };
  const fmtDate = value => value ? String(value).slice(0, 10) : '未安排';
  const courseName = id => state.courses.find(course => course.course_id === id)?.course_name || '未指定课程';
  function setView(view, push = true) {
    if (!views.includes(view)) view = 'today';
    state.view = view;
    if (push) history.replaceState(null, '', `#${view}`);
    $$('[data-view]').forEach(node => node.classList.toggle('is-active', node.dataset.view === view));
    $$('[data-route]').forEach(node => node.classList.toggle('is-active', node.dataset.route === view));
    $('#view-kicker').textContent = labels[view][0]; $('#view-title').textContent = '知债 · 考研错题工作台';
    const loaders = { today: loadToday, review: loadReview, capture: loadCapture, knowledge: loadKnowledge, settings: loadSettings };
    loaders[view]?.();
  }
  function renderCourseOptions() {
    const options = state.courses.map(c => `<option value="${esc(c.course_id)}">${esc(c.course_name)} · ${esc(c.course_group || '')}</option>`).join('');
    ['#course-select', '#capture-course', '#source-course', '#review-course-filter', '#bank-course-filter', '#bank-import-course'].forEach(selector => { const node = $(selector); if (!node) return; const old = node.value; const first = selector === '#course-select' ? '全部课程' : selector.includes('filter') ? '全部课程' : selector === '#bank-import-course' ? '导入到课程' : '未指定'; node.innerHTML = `<option value="">${first}</option>${options}`; if (old) node.value = old; });
    const selected = $('#course-select'); if (selected) selected.value = state.courseId;
    $('#course-context').textContent = state.courseId ? courseName(state.courseId) : '全部课程';
  }
  async function loadCourses() { try { const rows = await data('/api/courses'); const order = { politics: 0, english: 1, math: 2, professional: 3 }; state.courses = (rows || []).sort((a, b) => (order[a.subject_key] ?? 9) - (order[b.subject_key] ?? 9) || String(a.course_name).localeCompare(String(b.course_name), 'zh-CN')); renderCourseOptions(); renderCourseCards(); } catch (error) { toast(error.message); } }
  function renderCourseCards() {
    const html = state.courses.map(course => `<button class="course-card ${state.courseId === course.course_id ? 'is-selected' : ''}" data-course-card="${esc(course.course_id)}"><strong>${esc(course.course_name)}</strong><small>${esc(course.course_group || '自定义课程')}</small></button>`).join('');
    ['#today-course-list', '#knowledge-course-list'].forEach(selector => { const node = $(selector); if (node) node.innerHTML = html || '<div class="empty">还没有课程。</div>'; });
    $$('[data-course-card]').forEach(node => node.addEventListener('click', () => { state.courseId = node.dataset.courseCard; $('#course-select').value = state.courseId; renderCourseOptions(); loadToday(); loadKnowledge(); }));
  }
  async function loadToday() {
    try { const [due, wrong] = await Promise.all([data('/api/reviews/due'), data(`/api/wrong-questions${state.courseId ? `?course_id=${encodeURIComponent(state.courseId)}` : ''}`)]); state.due = due || []; $('#today-due-count').textContent = state.due.length; $('#today-wrong-count').textContent = (wrong || []).length; $('#today-course-count').textContent = state.courses.length; renderTodayDue(state.due[0]); renderCourseCards(); } catch (error) { $('#today-due-body').textContent = error.message; }
  }
  function renderTodayDue(item) { const title = $('#today-due-title'), body = $('#today-due-body'), badge = $('#today-due-badge'), button = $('#today-start-review'); if (!item) { title.textContent = '今天没有到期题'; body.textContent = '可以去收录一道新题，或者在知识区导入题库。'; badge.textContent = '空'; button.disabled = true; return; } title.textContent = item.question_text || item.question_image_status || '待补题面'; body.innerHTML = `<p>${esc(item.display_label || '已确认错题')} · 第 ${item.review_round || 1} 轮 · ${esc(fmtDate(item.due_at))}</p><p class="muted">${esc(item.reason_kind || '到期回测')} · ${esc(item.is_image_intake ? '图片错题' : '兼容题目')}</p>`; badge.textContent = item.is_image_intake ? '图片错题' : '待处理'; button.disabled = false; button.onclick = () => openReview(item); }
  async function loadReview() { try { const params = new URLSearchParams(); if (state.courseId) params.set('course_id', state.courseId); if ($('#review-error-filter')?.value) params.set('error_type', $('#review-error-filter').value); const [due, wrong] = await Promise.all([data('/api/reviews/due'), data(`/api/wrong-questions?${params}`)]); state.due = due || []; $('#review-queue-count').textContent = state.due.length; renderReviewQueue(state.due); renderWrongList(wrong || []); } catch (error) { toast(error.message); } }
  function renderReviewQueue(items) { const node = $('#review-queue'); node.innerHTML = items.length ? items.map(item => `<div class="list-row"><div class="list-row-main"><strong>${esc(item.question_text || item.question_image_status || '待补题面')}</strong><small>${esc(item.display_label || '错题')} · 第 ${item.review_round || 1} 轮 · 到期 ${esc(fmtDate(item.due_at))}</small></div><button class="button button-quiet" data-review-task="${esc(item.review_task_id)}">开始</button></div>`).join('') : '<div class="empty">没有到期回测。</div>'; $$('[data-review-task]', node).forEach(button => button.addEventListener('click', () => openReview(items.find(item => item.review_task_id === button.dataset.reviewTask)))); }
  function renderWrongList(items) { const node = $('#wrong-list'); node.innerHTML = items.length ? items.map(item => `<div class="list-row"><div class="list-row-main"><strong>${esc(item.question_text || '待补题面')}</strong><small>${esc(item.course_name || '未指定课程')} · ${esc(item.chapter || '待补章节')} · ${esc(errorLabels[item.error_type] || '待诊断')}</small></div><button class="button button-quiet" data-wrong-id="${esc(item.question_id)}">查看</button></div>`).join('') : '<div class="empty">还没有符合条件的已确认错题。</div>'; $$('[data-wrong-id]', node).forEach(button => button.addEventListener('click', () => openWrongDetail(button.dataset.wrongId))); }
  async function openReview(item) { if (!item) return; try { await data('/api/start', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ review_task_id: item.review_task_id }) }); const safe = await data(`/api/wrong-questions/${encodeURIComponent(item.question_id)}/review?review_task_id=${encodeURIComponent(item.review_task_id)}`); renderReviewDialog(safe, item); $('#review-dialog').showModal(); } catch (error) { toast(error.message); } }
  function renderReviewDialog(item, task) { $('#dialog-title').textContent = item.question_text || item.question_image_status || '待补题面'; $('#dialog-content').innerHTML = `<p class="muted">${esc(item.course_name || '未指定课程')} · ${esc(fmtDate(task?.due_at))}</p><div class="asset-grid">${(item.assets || []).map(asset => `<div class="asset-card"><img src="${esc(asset.media_url)}" alt="${esc(asset.original_filename || '题面')}"><small>${esc(asset.original_filename || '')}</small></div>`).join('') || '<p class="empty">题面图片待补充。</p>'}</div><div class="review-choice"><p><b>现在的判断</b></p><div class="filter-row"><button class="button button-quiet" data-review-state="会">会</button><button class="button button-quiet" data-review-state="不会">不会</button><button class="button button-quiet" data-review-state="不确定">不确定</button></div><p class="muted" id="review-state-note">选择后可以结束本轮，或上传新的完整过程。</p></div><form id="redo-form"><label>新的完整解题过程（可选）<textarea id="redo-text" placeholder="也可以只上传过程图片"></textarea></label><input id="redo-files" type="file" accept="image/*" multiple><div class="form-actions"><button class="button button-primary" type="submit">保存本轮回测</button><span class="inline-note">系统不会自动判定你已掌握</span></div></form>`; let stateChoice = ''; $$('[data-review-state]').forEach(button => button.addEventListener('click', () => { stateChoice = button.dataset.reviewState; $('#review-state-note').textContent = `本轮选择：${stateChoice}。仍可上传新的完整过程。`; })); $('#redo-form').addEventListener('submit', async event => { event.preventDefault(); try { const files = [...$('#redo-files').files]; const form = new FormData(); files.forEach(file => form.append('files', file, file.name)); form.append('review_task_id', item.review_task_id); form.append('response_text', $('#redo-text').value); form.append('completion_claim', stateChoice === '会' ? 'known' : 'complete'); const result = await data(`/api/wrong-questions/${encodeURIComponent(item.question_id)}/redo`, { method: 'POST', body: form }); const attemptId = result.attempt_id || result.draft?.draft_attempt_id; if (attemptId && (files.length || text($('#redo-text').value))) await data(`/api/attempts/${encodeURIComponent(attemptId)}/submit`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ response_text: $('#redo-text').value, completion_claim: stateChoice === '会' ? 'known' : 'complete' }) }); $('#review-dialog').close(); toast('本轮回测已保存'); loadReview(); loadToday(); } catch (error) { toast(error.message); } }); }
  async function openWrongDetail(id) { try { const item = await data(`/api/wrong-questions/${encodeURIComponent(id)}`); $('#dialog-title').textContent = item.question_text || '错题详情'; $('#dialog-content').innerHTML = `<p class="muted">${esc(item.course_name || '未指定课程')} · ${esc(item.grading?.chapter || '待补章节')} · ${esc(errorLabels[item.grading?.error_type] || '待诊断')}</p><div class="detail-copy"><p><b>错误原因</b><br>${esc(item.grading?.error_reason || '待补充')}</p><p><b>首次出错步骤</b><br>${esc(item.grading?.error_breakpoint || '待补充')}</p><p><b>正确思路</b><br>${esc(item.grading?.correct_approach || '待补充')}</p><p><b>知识点</b><br>${esc(item.grading?.knowledge_point || '待补充')} · ${esc(item.grading?.question_type || '待补充')}</p></div><button class="button button-primary" data-route="capture">继续整理图片</button>`; $('#review-dialog').showModal(); } catch (error) { toast(error.message); } }
  async function loadCapture() { try { const items = await data('/api/intake'); renderIntakeList(items || []); await loadSources(); if (state.selectedIntake) await selectIntake(state.selectedIntake); } catch (error) { toast(error.message); } }
  async function loadSources() { try { const items = await data('/api/sources?limit=12'); $('#source-list').innerHTML = items.length ? items.map(item => `<div class="list-row"><div class="list-row-main"><strong>${esc(item.source_name || item.name || '资料')}</strong><small>${esc(item.course_name || item.subject_key || '未指定课程')} · ${esc(item.parse_state || '待解析')} · ${esc(item.passage_count ?? 0)} 段</small></div><span class="badge">${item.parse_state === 'ready' ? '已解析' : '待增强'}</span></div>`).join('') : '<div class="empty">还没有已保存资料。</div>'; } catch (error) { $('#source-list').innerHTML = `<div class="empty">暂时无法读取资料：${esc(error.message)}</div>`; } }
  async function saveSource(event) { event.preventDefault(); const file = $('#source-file').files[0], url = text($('#source-url').value), rawText = text($('#source-text').value); if (!file && !url && !rawText) return toast('请先选择文件、填写网页 URL 或粘贴资料文本'); try { let result; if (file) { const form = new FormData(); form.append('files', file, file.name); form.append('source_name', file.name); form.append('course_id', $('#source-course').value); const response = await fetch('/api/capture/source', { method: 'POST', body: form }); const body = await response.json(); if (!response.ok || body.error) throw new Error(body.error?.message || '保存资料失败'); result = body.data; } else { result = await data('/api/capture/source', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_name: url || '粘贴资料', source_url: url, raw_text: rawText, course_id: $('#source-course').value }) }); } $('#source-status').textContent = '资料已保存，可在列表中重试增强。'; $('#source-form').reset(); await loadSources(); toast('资料已保存'); if (result?.source_artifact_id) { try { await data('/api/enrich', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ source_artifact_id: result.source_artifact_id }) }); await loadSources(); } catch (_) {} } } catch (error) { toast(error.message); } }
  function renderIntakeList(items) { const node = $('#intake-list'); node.innerHTML = items.length ? items.map(item => `<div class="list-row"><div class="list-row-main"><strong>${esc(item.intake_id)}</strong><small>${esc(item.asset_count || 0)} 张 · ${esc(item.course_name || item.subject_key || '未指定课程')} · ${esc(item.resolution_label || item.state || '待处理')}</small></div><button class="button button-quiet" data-intake-id="${esc(item.intake_id)}">打开</button></div>`).join('') : '<div class="empty">还没有图片收录。</div>'; $$('[data-intake-id]', node).forEach(button => button.addEventListener('click', () => selectIntake(button.dataset.intakeId))); }
  function renderPreviews() { const node = $('#upload-previews'); node.innerHTML = state.pendingFiles.map(file => `<div class="preview-item"><img src="${URL.createObjectURL(file)}" alt="${esc(file.name)}"><small>${esc(file.name)}</small></div>`).join(''); }
  async function uploadIntake(event) { event.preventDefault(); if (!state.pendingFiles.length) return toast('请先选择图片'); try { const form = new FormData(); state.pendingFiles.forEach(file => form.append('files', file, file.name)); form.append('course_id', $('#capture-course').value); form.append('subject_key', $('#capture-subject').value); form.append('roles', JSON.stringify(state.pendingFiles.map(() => ''))); const item = await data('/api/intake/batches', { method: 'POST', body: form }); state.pendingFiles = []; $('#image-files').value = ''; renderPreviews(); state.selectedIntake = item.intake_id; await selectIntake(item.intake_id); await loadCapture(); toast('原图已保存，正在生成分析草稿'); try { await data(`/api/intake/${encodeURIComponent(item.intake_id)}/analyze`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); await data(`/api/intake/${encodeURIComponent(item.intake_id)}/resolve`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); await selectIntake(item.intake_id); } catch (error) { toast(`原图已保存，分析稍后重试：${error.message}`); } } catch (error) { toast(error.message); } }
  async function selectIntake(id) { try { const item = await data(`/api/intake/${encodeURIComponent(id)}`); state.selectedIntake = id; renderIntakeDetail(item); } catch (error) { toast(error.message); } }
  function renderIntakeDetail(item) { const draft = item.draft_fields || {}; $('#intake-detail-title').textContent = `${item.intake_id} · ${item.course_name || item.subject_key || '未指定课程'}`; $('#intake-detail-state').textContent = draft.confirmed_question_id ? '已确认' : draft.analysis_status === 'draft' ? '待确认' : item.state || '原图'; $('#append-images').disabled = false; $('#capture-selection-note').textContent = `${item.assets?.length || 0} 张图片 · ${draft.analysis_status === 'draft' ? '分析完成' : '可继续编辑'}`; $('#intake-assets').classList.toggle('empty-state', !(item.assets || []).length); $('#intake-assets').innerHTML = (item.assets || []).length ? item.assets.map(asset => `<div class="asset-card"><img src="${esc(asset.media_url)}" alt="${esc(asset.original_filename || '')}"><small>${esc(asset.original_filename || '')}</small><select data-asset-role="${esc(asset.asset_id)}"><option value="">未指定</option><option value="question" ${asset.role === 'question' ? 'selected' : ''}>题面</option><option value="my_process" ${asset.role === 'my_process' ? 'selected' : ''}>我的过程</option><option value="reference" ${asset.role === 'reference' ? 'selected' : ''}>参考解</option><option value="mixed" ${asset.role === 'mixed' ? 'selected' : ''}>题面+过程</option></select></div>`).join('') : '还没有保存的图片。'; $$('[data-asset-role]').forEach(select => select.addEventListener('change', () => patchIntake(item.intake_id, { assets: [{ asset_id: select.dataset.assetRole, role: select.value }] }))); $('#confirm-intake').disabled = !!draft.confirmed_question_id; $('#confirm-intake').onclick = async () => { try { await data(`/api/intake/${encodeURIComponent(item.intake_id)}/confirm`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' }); toast('已确认进入正式错题本'); await selectIntake(item.intake_id); } catch (error) { toast(error.message); } }; renderAnalysisForm(item); }
  function renderAnalysisForm(item) { const draft = item.draft_fields || {}; const fields = [['question_text', '题面', 'textarea'], ['reference_answer', '正确答案或参考解', 'textarea'], ['error_type', '错误类型', 'select'], ['error_reason', '哪里没做好', 'textarea'], ['error_breakpoint', '第一次出错的具体步骤', 'textarea'], ['knowledge_point', '关联知识点', 'input'], ['chapter', '关联章节', 'input'], ['question_type', '题型或方法', 'input']]; $('#analysis-form').innerHTML = fields.map(([key, label, type]) => { const value = text(draft[key]); if (type === 'select') return `<label>${label}<select data-draft-field="${key}"><option value="">待确认</option>${Object.entries(errorLabels).map(([id, name]) => `<option value="${id}" ${value === id ? 'selected' : ''}>${name}</option>`).join('')}</select></label>`; return `<label>${label}${type === 'textarea' ? `<textarea data-draft-field="${key}">${esc(value)}</textarea>` : `<input data-draft-field="${key}" value="${esc(value)}">`}</label>`; }).join('') + `<div class="analysis-actions"><button type="button" class="button button-quiet" id="save-analysis">保存字段</button><span class="inline-note">候选字段可以全部手动改。</span></div>`; $('#save-analysis').onclick = async () => { const draft_fields = {}; $$('[data-draft-field]').forEach(field => draft_fields[field.dataset.draftField] = field.value); try { await patchIntake(item.intake_id, { draft_fields }); toast('分析字段已保存'); } catch (error) { toast(error.message); } }; }
  async function patchIntake(id, payload) { const item = await data(`/api/intake/${encodeURIComponent(id)}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); renderIntakeDetail(item); return item; }
  async function loadKnowledge() { try { const courseQuery = state.courseId ? `?course_id=${encodeURIComponent(state.courseId)}` : ''; const nav = await data(`/api/knowledge${courseQuery}`); renderKnowledge(nav || {}); const bank = await data(`/api/question-bank${courseQuery}`); renderBank(bank || []); } catch (error) { toast(error.message); } }
  function renderKnowledge(nav) { const subjects = nav.subjects || []; $('#knowledge-count').textContent = nav.question_count || 0; $('#knowledge-title').textContent = state.courseId ? courseName(state.courseId) : '全部课程'; $('#knowledge-summary-title').textContent = state.courseId ? courseName(state.courseId) : '选择一门课程'; $('#knowledge-summary-lines').innerHTML = `<div><span>已确认题目</span><b>${nav.question_count || 0}</b></div><div><span>关联资料</span><b>${nav.source_count || 0}</b></div><div><span>课程边界</span><b>${state.courseId ? '独立' : '全部'}</b></div>`; const tree = []; subjects.forEach(subject => (subject.chapters || []).forEach(chapter => (chapter.knowledge_points || []).forEach(point => tree.push(`<div class="tree-item"><strong>${esc(point.knowledge_point)}</strong><small>${esc(subject.label)} · ${esc(chapter.chapter)} · ${point.questions?.length || 0} 题</small></div>`)))); $('#knowledge-tree').innerHTML = tree.length ? tree.join('') : '<div class="empty">确认错题后，课程知识树会从题目和资料中长出来。</div>'; }
  async function loadBank() { try { const params = new URLSearchParams(); if ($('#bank-course-filter').value) params.set('course_id', $('#bank-course-filter').value); renderBank(await data(`/api/question-bank?${params}`)); } catch (error) { toast(error.message); } }
  function renderBank(items) { const keyword = text($('#bank-keyword')?.value).toLowerCase(); const filtered = keyword ? items.filter(item => [item.question_text, item.chapter, item.knowledge_point, item.question_type].join(' ').toLowerCase().includes(keyword)) : items; const node = $('#bank-list'); node.innerHTML = filtered.length ? filtered.map(item => `<div class="list-row"><div class="list-row-main"><strong>${esc(item.question_text || '待补题面')}</strong><small>${esc(item.course_name || courseName(item.course_id))} · ${esc(item.chapter || '待补章节')} · ${esc(item.question_type || '待补题型')} · 难度 ${esc(item.difficulty || '—')}</small></div><span class="badge">${esc(item.source || '题库')}</span></div>`).join('') : '<div class="empty">当前课程还没有导入题库。</div>'; }
  async function previewBank() { const file = $('#bank-file').files[0]; if (!file) return toast('请先选择 CSV 或 JSON'); const form = new FormData(); form.append('file', file, file.name); form.append('course_id', $('#bank-import-course').value); try { state.bankPreview = await data('/api/question-bank/preview', { method: 'POST', body: form }); $('#bank-preview-result').textContent = `共 ${state.bankPreview.total_rows || state.bankPreview.items?.length || 0} 行，${state.bankPreview.errors?.length || 0} 个错误`; $('#bank-import').disabled = !!state.bankPreview.errors?.length; } catch (error) { toast(error.message); } }
  async function importBank() { if (!state.bankPreview) return; try { const file = $('#bank-file').files[0], form = new FormData(); form.append('file', file, file.name); form.append('course_id', $('#bank-import-course').value); await data('/api/question-bank/import', { method: 'POST', body: form }); toast('题库已导入'); state.bankPreview = null; $('#bank-import').disabled = true; loadKnowledge(); } catch (error) { toast(error.message); } }
  async function loadPolitics() { try { const politicsCourse = state.courses.find(course => course.subject_key === 'politics'); if (!politicsCourse) { state.politicsItems = []; renderPolitics(); return; } const items = await data(`/api/question-bank?course_id=${encodeURIComponent(politicsCourse.course_id)}`); state.politicsItems = items || []; state.politicsIndex = 0; renderPolitics(); } catch (error) { toast(error.message); } }
  function renderPolitics() { const item = state.politicsItems[state.politicsIndex], node = $('#politics-question'); if (!item) { node.textContent = '还没有政治题库，请在题库页导入。'; return; } const options = typeof item.options === 'string' ? item.options.split('|').map(value => value.trim()) : Object.entries(item.options || {}).map(([key, value]) => `${key}. ${value}`); node.innerHTML = `<h4>${esc(item.question_text || '题面')}</h4><div class="question-options">${options.map((option, index) => `<label class="question-option"><input type="radio" name="politics-answer" value="${esc(Object.keys(item.options || {})[index] || option.slice(0,1))}">${esc(option)}</label>`).join('')}</div><button class="button button-primary" id="politics-submit">提交答案</button>`; $('#politics-submit').onclick = async () => { const selected = $('input[name="politics-answer"]:checked'); if (!selected) return toast('先选择一个答案'); try { const result = await data(`/api/question-bank/${encodeURIComponent(item.question_bank_item_id)}/answer`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ selected_answer: selected.value }) }); node.insertAdjacentHTML('beforeend', `<p class="${result.is_correct ? '' : 'muted'}"><b>${result.is_correct ? '回答正确' : '回答错误'}</b> · ${esc(result.explanation || '暂无解析')}</p>`); } catch (error) { toast(error.message); } }; }
  async function loadSettings() { try { const settings = await data('/api/settings/model'); fillSettings('primary', settings.primary); fillSettings('fallback', settings.fallback); $('#settings-status').textContent = '已读取本地设置'; } catch (error) { $('#settings-status').textContent = error.message; } }
  function fillSettings(slot, value = {}) { $(`#${slot}-protocol`).value = value.protocol || 'openai_chat'; $(`#${slot}-base-url`).value = value.base_url || ''; $(`#${slot}-model`).value = value.model || ''; $(`#${slot}-key`).value = ''; }
  async function saveSettings(event) { event.preventDefault(); try { await data('/api/settings/model', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ primary: { protocol: $('#primary-protocol').value, base_url: $('#primary-base-url').value, model: $('#primary-model').value, api_key: $('#primary-key').value }, fallback: { protocol: $('#fallback-protocol').value, base_url: $('#fallback-base-url').value, model: $('#fallback-model').value, api_key: $('#fallback-key').value } }) }); $('#settings-status').textContent = '已保存'; toast('模型设置已保存'); } catch (error) { toast(error.message); } }
  async function createCourse(event) { event.preventDefault(); try { await data('/api/courses', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ course_group: $('#new-course-group').value, course_name: $('#new-course-name').value, subject_key: 'professional' }) }); $('#course-dialog').close(); $('#course-form').reset(); await loadCourses(); toast('课程已创建'); } catch (error) { toast(error.message); } }
  function bind() {
    $$('[data-route]').forEach(node => node.addEventListener('click', () => setView(node.dataset.route)));
    window.addEventListener('hashchange', () => setView(location.hash.slice(1), false));
    $('#course-select').addEventListener('change', event => { state.courseId = event.target.value; renderCourseOptions(); renderCourseCards(); loadToday(); if (state.view === 'review') loadReview(); if (state.view === 'knowledge') loadKnowledge(); });
    $('#theme-toggle').addEventListener('click', () => { const next = document.documentElement.dataset.theme === 'dark' ? '' : 'dark'; document.documentElement.dataset.theme = next; localStorage.setItem('kaoyan-theme', next); });
    $('#image-files').addEventListener('change', event => { state.pendingFiles = [...event.target.files]; renderPreviews(); }); $('#image-upload-form').addEventListener('submit', uploadIntake); $('#capture-refresh').addEventListener('click', loadCapture); $('#source-refresh').addEventListener('click', loadSources); $('#source-form').addEventListener('submit', saveSource); $('#append-images').addEventListener('click', async () => { if (!state.selectedIntake || !state.pendingFiles.length) return toast('选择图片和当前批次后再追加'); const form = new FormData(); state.pendingFiles.forEach(file => form.append('files', file, file.name)); try { await data(`/api/intake/${encodeURIComponent(state.selectedIntake)}/assets`, { method: 'POST', body: form }); state.pendingFiles = []; $('#image-files').value = ''; renderPreviews(); await selectIntake(state.selectedIntake); toast('图片已追加'); } catch (error) { toast(error.message); } });
    $('#review-refresh').addEventListener('click', loadReview); $('#review-course-filter').addEventListener('change', event => { state.courseId = event.target.value; $('#course-select').value = state.courseId; renderCourseOptions(); loadReview(); }); $('#review-error-filter').addEventListener('change', loadReview); $('#new-course-button').addEventListener('click', () => $('#course-dialog').showModal()); $('#course-form').addEventListener('submit', createCourse); $('#bank-refresh').addEventListener('click', loadBank); $('#bank-search').addEventListener('click', loadBank); $('#bank-preview').addEventListener('click', previewBank); $('#bank-import').addEventListener('click', importBank); $('#politics-load').addEventListener('click', loadPolitics); $('#settings-form').addEventListener('submit', saveSettings); $$('[data-close-dialog]').forEach(button => button.addEventListener('click', () => $('#review-dialog').close())); $$('[data-knowledge-tab]').forEach(button => button.addEventListener('click', () => { $$('[data-knowledge-tab]').forEach(tab => tab.classList.toggle('is-active', tab === button)); $$('[data-tab-panel]').forEach(panel => panel.classList.toggle('is-active', panel.dataset.tabPanel === button.dataset.knowledgeTab)); if (button.dataset.knowledgeTab === 'politics') loadPolitics(); }));
  }
  document.documentElement.dataset.theme = localStorage.getItem('kaoyan-theme') || '';
  bind(); loadCourses().then(() => setView(state.view, false));
})();
